CREATE TABLE "productos" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug_es" varchar(100) NOT NULL,
	"slug_en" varchar(100) NOT NULL,
	"name" varchar(100) NOT NULL,
	"tagline_es" varchar(200) NOT NULL,
	"tagline_en" varchar(200) NOT NULL,
	"description_es" text NOT NULL,
	"description_en" text NOT NULL,
	"external_url" varchar(300) NOT NULL,
	"external_cta_es" varchar(100) DEFAULT 'Ver producto' NOT NULL,
	"external_cta_en" varchar(100) DEFAULT 'View product' NOT NULL,
	"icp_es" varchar(300) NOT NULL,
	"icp_en" varchar(300) NOT NULL,
	"category_es" varchar(100) NOT NULL,
	"category_en" varchar(100) NOT NULL,
	"pricing_from" integer,
	"pricing_currency" varchar(10) DEFAULT 'USD',
	"pricing_label_es" varchar(100),
	"pricing_label_en" varchar(100),
	"pricing_note_es" varchar(200),
	"pricing_note_en" varchar(200),
	"metrics" jsonb,
	"features" jsonb,
	"comparison_table" jsonb,
	"faqs" jsonb,
	"accent_color" varchar(20) DEFAULT 'cyan' NOT NULL,
	"hero_effect" varchar(20) DEFAULT 'particles' NOT NULL,
	"og_image" varchar(500),
	"seo_title_es" varchar(100) NOT NULL,
	"seo_title_en" varchar(100) NOT NULL,
	"seo_description_es" varchar(200) NOT NULL,
	"seo_description_en" varchar(200) NOT NULL,
	"schema_category" varchar(100) DEFAULT 'BusinessApplication',
	"status" "content_status" DEFAULT 'draft' NOT NULL,
	"translation_status_en" "translation_status" DEFAULT 'pending' NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"published_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "productos_slug_es_unique" UNIQUE("slug_es"),
	CONSTRAINT "productos_slug_en_unique" UNIQUE("slug_en")
);
