ALTER TABLE "home_content" ADD COLUMN "hero_cta_primary_url" varchar(500);--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "hero_cta_secondary_url" varchar(500);--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "trust_bar_title_es" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "trust_bar_title_en" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "pillars_subtitle_es" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "pillars_subtitle_en" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "cases_section_subtitle_es" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "cases_section_subtitle_en" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "cases_section_footer_es" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "cases_section_footer_en" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "cases_section_cta_es" varchar(255);--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "cases_section_cta_en" varchar(255);--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "products_strip_title_es" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "products_strip_title_en" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "products_strip_cta_es" varchar(255);--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "products_strip_cta_en" varchar(255);--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "map_title_es" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "map_title_en" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "map_subtitle_es" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "map_subtitle_en" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "map_metrics" jsonb;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "why_us_title_es" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "why_us_title_en" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "why_us_subtitle_es" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "why_us_subtitle_en" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "why_us_items" jsonb;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "faqs_title_es" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "faqs_title_en" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "final_cta_bullets" jsonb;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "final_cta_primary_es" varchar(255);--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "final_cta_primary_en" varchar(255);--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "final_cta_primary_url" varchar(500);--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "final_cta_secondary_es" varchar(255);--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "final_cta_secondary_en" varchar(255);--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "final_cta_secondary_url" varchar(500);--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "final_cta_fine_print_es" text;--> statement-breakpoint
ALTER TABLE "home_content" ADD COLUMN "final_cta_fine_print_en" text;